const footerinformation = [
    { info: "Testing conducted by Apple in October 2020 using preproduction MacBook Air systems with Apple M1 chip and 8-core GPU, configured with 8GB of RAM and 512GB SSD. The Apple TV app movie playback test measures battery life by playing back HD 1080p content with display brightness set to 8 clicks from bottom. Battery life varies by use and configuration. See apple.com/eg/batteries for more information." },
    { info: "fTesting conducted by Apple in August and September 2021 using JetStream 2, MotionMark 1.2, and Speedometer 2.0 performance benchmarks. Tested with prerelease Safari 15 and latest stable versions of Chrome, Microsoft Edge, and Firefox at the time of testing on: 13-inch MacBook Pro systems with Apple M1 and prerelease macOS Monterey, and Intel Core i7-based PC systems with Intel Iris Xe Graphics and Windows 10 Pro; iPad Pro 12.9-inch (5th generation) units with prerelease iPadOS 15, and Intel Core i7-based PC systems with Intel Iris Xe Graphics and Windows 10 Pro; and iPhone 12 Pro Max with prerelease iOS 15, and Qualcomm Snapdragon 888-based smartphones with Android 11. Devices tested with a WPA2 Wi-Fi network connection. Performance will vary based on usage, system configuration, network connection, and other factors." },
    { info: "f1TB = 1 trillion bytes; actual formatted capacity less." },
    { info: "Speeds are based on theoretical throughput and may vary." },
    { info: "Screen size is measured diagonally. The displays on the 13-inch and 15-inch MacBook Air with M2 and the 14-inch and 16-inch MacBook Pro have rounded corners at the top. When measured as a standard rectangular shape, the screens are 13.6 inches, 15.3 inches, 14.2 inches, and 16.2 inches diagonally (actual viewable area is less)." },
    { info: "Testing conducted by Apple in April and May 2023 using preproduction 15‑inch MacBook Air systems with Apple M2, 8-core CPU, 10-core GPU, 8GB of RAM, and 256GB SSD. The Apple TV app movie playback test measures battery life by playing back HD 1080p content with display brightness set to 8 clicks from bottom. Battery life varies by use and configuration. See apple.com/eg/batteries for more information." },
    { info: "Testing conducted by Apple in May 2022 using preproduction 13‑inch MacBook Pro systems with Apple M2, 8‑core CPU, 10‑core GPU, 8GB of RAM, and 256GB SSD. The wireless web test measures battery life by wirelessly browsing 25 popular websites with display brightness set to 8 clicks from bottom. The Apple TV app movie playback test measures battery life by playing back HD 1080p content with display brightness set to 8 clicks from bottom. Battery life varies by use and configuration. See apple.com/eg/batteries for more information." },
    { info: "Testing conducted by Apple in November and December 2022 using preproduction 16‑inch MacBook Pro systems with Apple M2 Pro, 12-core CPU, 19-core GPU, 16GB of RAM, and 1TB SSD. The wireless web test measures battery life by wirelessly browsing 25 popular websites with display brightness set to 8 clicks from bottom. The Apple TV app movie playback test measures battery life by playing back HD 1080p content with display brightness set to 8 clicks from bottom. Battery life varies by use and configuration. See apple.com/eg/batteries for more information." },
]


export default footerinformation;